name: Deploy to Windows

on:
  pull_request:
    types: [closed]
    branches:
      - main  # Only trigger for PRs merged into main

jobs:
  windows_x86_64:
      if: github.event.pull_request.merged == true
      runs-on: windows-latest
      steps:
          - uses: actions/checkout@v4
          
          - name: Installing Choco
            shell: pwsh
            run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

          - name: Install tooling with Choco
            shell: pwsh
            run: |
                choco install cmake.install --version=3.31.6
                cmake --version
                choco install llvm --version=20.1.4
                clang++ --version
                choco install git make mingw
          
          - name: Pip installing conan
            shell: pwsh
            run: pip install conan
          
          - name: Setting up conan profiles
            shell: pwsh
            run: conan config install -sf profiles/x86_64/Windows/ -tf profiles https://github.com/engine3d-dev/conan-config.git
          
          - name: Setting up remote repositories
            shell: pwsh
            run: |
              conan remote add engine3d-conan https://libhal.jfrog.io/artifactory/api/conan/engine3d-conan
              conan remote add libhal-trunk https://libhal.jfrog.io/artifactory/api/conan/trunk-conan
          
          - name: Creating Release build for audio-cpp
            shell: pwsh
            run: conan create . -b missing -s build_type=Release -pr windows_x86_64
          
          - name: Creating Debug build for audio-cpp
            shell: pwsh
            run: conan create . -b missing -s build_type=Debug -pr windows_x86_64
          
          - name: Creating MinSizeRel build for audio-cpp
            shell: pwsh
            run: conan create . -b missing -s build_type=MinSizeRel -pr windows_x86_64
          
          - name: Login to JFrog
            shell: pwsh
            run: conan remote login -p ${{ secrets.JFROG_USER_TOKEN_ID }} engine3d-conan ${{ secrets.JFROG_USERNAME }}

          # - name: Deploy audio-cpp to JFrog remote repositories
          #   shell: pwsh
          #   run: |
          #     conan upload audio-cpp/2.0 --r=engine3d-conan --confirm
